package com.hostelmanagement.controller;
import com.hostelmanagement.ai.AIService; import com.hostelmanagement.entity.*; import com.hostelmanagement.repository.*; import com.hostelmanagement.service.RoomService; import jakarta.validation.Valid; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") public class ApiController { private final StudentRepository students; private final RoomRepository rooms; private final ComplaintRepository complaints; private final AttendanceRepository attendance; private final LeaveRequestRepository leaves; private final RoomService roomService; private final AIService ai;
 public ApiController(StudentRepository s,RoomRepository r,ComplaintRepository c,AttendanceRepository a,LeaveRequestRepository l,RoomService rs,AIService ai){students=s;rooms=r;complaints=c;attendance=a;leaves=l;roomService=rs;this.ai=ai;}
 @GetMapping("/students") public List<Student> students(){return students.findAll();} @PostMapping("/students") public Student create(@Valid @RequestBody Student s){return students.save(s);} @GetMapping("/rooms") public List<Room> rooms(){return rooms.findAll();}
 @PostMapping("/room-allocations/{studentId}/{roomId}") public Student allocate(@PathVariable Long studentId,@PathVariable Long roomId){return roomService.allocate(studentId,roomId);} @GetMapping("/room-allocations/recommend/{studentId}") public List<Map<String,Object>> recommend(@PathVariable Long studentId){return roomService.recommend(students.findById(studentId).orElseThrow());}
 @PostMapping("/complaints") public Complaint complaint(@RequestBody Complaint c){return complaints.save(c);} @GetMapping("/complaints") public List<Complaint> complaints(){return complaints.findAll();}
 @PostMapping("/ai/complaint-analysis") public Map<String,Object> analyze(@RequestBody Map<String,String> b){return ai.complaint(b.getOrDefault("text",""));}
 @PostMapping("/ai/chat") public Map<String,String> chat(@RequestBody Map<String,String> b){return Map.of("answer",ai.chat(b.getOrDefault("question","")));}
 @GetMapping("/dashboard") public Map<String,Object> dashboard(){long total=students.count(), occupied=students.findAll().stream().filter(s->s.getRoom()!=null).count(); return Map.of("students",total,"rooms",rooms.count(),"occupiedBeds",occupied,"availableStudentsWithoutRoom",Math.max(0,total-occupied),"complaints",complaints.count(),"attendanceRecords",attendance.count(),"leaveRequests",leaves.count());}
}
